### ISSUE TITLE
Many errormessages of the QualityCheck-Sourcecode on check of WinCC OA Demo-Application 3.19

### ISSUE THREAD

**Issue by rglockETM** [siemens/CtrlppCheck#78] opened 2023-11-08 14:58 UTC
Include the QualityCheck to the DemoApplication, start the Gedi and start the "CtrlCheck (static)" from the Dock Window:

Tons of messages like this:

WCCOAui      (1), 2023.11.08 15:57:28.214, CTRL, WARNING,    10/oaUnit_errors, (FAILED) Testfall 'scripts/libs/CommunicationCenter.ctl' fehlgeschlagen, 
  ErrMsg: Undefined variable: gdaNewUserData (undefinedVariable)
  Note: scripts/libs/CommunicationCenter.ctl
  StackTrace: , 
    Module: WinCCOA_QualityChecks
    Panel: D:\Projekte\3.19\WinCCOA_QualityChecks\panels\vision\gedi\welcomePage.pnl [WinCCOA - Quality Checks Ergebnisse]
    Object: 22 named: "btn_QgCtrlppCheck" of type: PUSH_BUTTON
    Script: Clicked
    Library: D:\Projekte\3.19\WinCCOA_QualityChecks\scripts\libs\classes\QualityGates\QgVersionResult.ctl
    Line: 548
WCCOAui      (1), 2023.11.08 15:57:28.216, CTRL, WARNING,    10/QgBase, Assertion return error: Undefined variable: gdaOldUserData (undefinedVariable)
WCCOAui      (1), 2023.11.08 15:57:28.216, CTRL, WARNING,    10/oaUnit_errors, (FAILED) Testfall 'scripts/libs/CommunicationCenter.ctl' fehlgeschlagen, 
  ErrMsg: Undefined variable: gdaOldUserData (undefinedVariable)
  Note: scripts/libs/CommunicationCenter.ctl
  StackTrace: , 
    Module: WinCCOA_QualityChecks
    Panel: D:\Projekte\3.19\WinCCOA_QualityChecks\panels\vision\gedi\welcomePage.pnl [WinCCOA - Quality Checks Ergebnisse]
    Object: 22 named: "btn_QgCtrlppCheck" of type: PUSH_BUTTON
    Script: Clicked
    Library: D:\Projekte\3.19\WinCCOA_QualityChecks\scripts\libs\classes\QualityGates\QgVersionResult.ctl
    Line: 548
WCCOAui      (1), 2023.11.08 15:57:28.218, CTRL, WARNING,    10/QgBase, Assertion return error: Undefined variable: gUserIndex (undefinedVariable)
WCCOAui      (1), 2023.11.08 15:57:28.219, CTRL, WARNING,    10/oaUnit_errors, (FAILED) Testfall 'scripts/libs/CommunicationCenter.ctl' fehlgeschlagen, 
  ErrMsg: Undefined variable: gUserIndex (undefinedVariable)
  Note: scripts/libs/CommunicationCenter.ctl
  StackTrace: , 
    Module: WinCCOA_QualityChecks
    Panel: D:\Projekte\3.19\WinCCOA_QualityChecks\panels\vision\gedi\welcomePage.pnl [WinCCOA - Quality Checks Ergebnisse]
    Object: 22 named: "btn_QgCtrlppCheck" of type: PUSH_BUTTON
    Script: Clicked
    Library: D:\Projekte\3.19\WinCCOA_QualityChecks\scripts\libs\classes\QualityGates\QgVersionResult.ctl

**Comment by dhoegerlETM** [comment] 2023-11-09 06:44
@mPokornyETM introduced regression here?

**Comment by mPokornyETM** [comment] 2023-11-09 15:33
No, when you look in the logs. There are findigs. The tool just write the output also in the log file. That means, this are not warnigs from the tool but warnings about failures in the DemoApplication.

My proposal is to change the log output. I work currently on better logs, because many of them are not sure, what their means.
So I can change the ouptut format (currently did it in my local development version). Or when we want we shall skipp it. Because you have the result in the result panel as well.

Anyway, this is not a bug, but feature request.

**Comment by dhoegerlETM** [comment] 2023-11-09 20:00
I see... But a) how do we identify that the reported issues are from DemoApplication and not from our QualityChecks subproject (as suggested by script paths) ?

@rglockETM please create an internal item for reworking the DemoApplication accordingly - I'll close this item as it is out of scope here.

**Closed by dhoegerlETM** 2023-11-09 20:00 UTC
Labels: bug

**Comment by mPokornyETM** [comment] 2023-11-10 13:13
@rglockETM one of my tpoic is to bind this tool into WinC OA framework. In that case it will be possible to check all subprojects and provide reports (in Jnekins also woth history) When this works, I will provide internall isues as well. But we need some machanismus to check the code on every changes, Otherwise it makes no sense (not now)
